DATA_DIR = 'scrapeData'

FILE_DELIM = '-'
FILE_SUFFIX = '.yml'

TXT_ERR_DIR = 'Could not verify directory: {}'
TXT_ERR_EXCEPT = 'An exception occurred while {}: {}'
TXT_ERR_SAVE = 'Could not save file: {}'

TXT_AUTHOR = 'author'
TXT_BANNED = 'banned'
TXT_COMMENTS = 'comments'
TXT_CONTRIB = 'contributor'
TXT_DEST = 'dest'
TXT_DISPLAY_NAME = 'display_name'
TXT_FETCHED = 'fetched'
TXT_ID = 'id'
TXT_KARMA = 'karma'
TXT_NAME = 'name'
TXT_PATH = 'path'
TXT_REPLIES = 'replies'
TXT_START = 'Scraping'
TXT_SAVING = 'Saving {} data'
TXT_SUBMISSION = 'submission'
TXT_SUBREDDIT = 'subreddit'
TXT_TYPE = 'type'
TXT_UTC_STAMP = 'utc_timestamp'
