CMD_DELIM = '.'

SCRAPE_DIR = 'scrape_data'

FILE_DELIM = '-'
FILE_SUFFIX = '.yml'

TXT_ERR_DIR = 'Could not verify directory: {}'
TXT_ERR_EXCEPT = 'An exception occurred while {}: {}'
TXT_ERR_SAVE = 'Could not save file: {}'

TXT_AUTHOR = 'author'
TXT_BANNED = 'banned'
TXT_COMMENTS = 'comments'
TXT_CONTRIB = 'contributor'
TXT_DEST = 'dest'
TXT_DISPLAY_NAME = 'display_name'
TXT_FETCHING = 'fetching'
TXT_FETCHED = 'fetched'
TXT_ID = 'id'
TXT_INBOX = 'inbox'
TXT_KARMA = 'karma'
TXT_MESSAGE = 'message'
TXT_MULTIREDDIT = 'multireddit'
TXT_NAME = 'name'
TXT_PATH = 'path'
TXT_REDDITOR = 'redditor'
TXT_REPLIES = 'replies'
TXT_START = 'Scraping'
TXT_SAVING = 'Saving {} data'
TXT_SCRAPE = 'scrape'
TXT_SUBMISSION = 'submission'
TXT_SUBREDDIT = 'subreddit'
TXT_TYPE = 'type'
TXT_USER = 'user'
TXT_UTC_STAMP = 'utc_timestamp'
